name: Automerge
on:
  workflow_dispatch:
    inputs:
      pr:
        type: number
        required: true
        description: Id of the pr
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c
        with:
          app_id: ${{ secrets.PROJEN_APP_ID }}
          private_key: ${{ secrets.PROJEN_APP_PRIVATE_KEY }}
          permissions: '{"pull_requests":"write","contents":"write"}'
      - run: gh pr merge ${{ github.event.inputs.pr }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
